name: Build macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Enable macOS desktop support
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos --release

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create DMG
        run: |
          mkdir -p dist
          create-dmg \
            --volname "Libra Sheet" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            "dist/Libra Sheet.dmg" \
            "build/macos/Build/Products/Release/Libra Sheet.app"

      # - name: Upload DMG artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: LibraSheet-macos-dmg
      #     path: "dist/Libra Sheet.dmg"

      - name: Upload DMG to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Latest macOS Build
          files: "dist/Libra Sheet.dmg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
